//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int EmpId { get; set; }
        public string EmpIdCardNo { get; set; }
        public string EmpName { get; set; }
        public string EmpGender { get; set; }
        public Nullable<System.DateTime> EmpJoinDate { get; set; }
        public Nullable<int> EmpAge { get; set; }
        public string EmpAddress { get; set; }
        public string EmpPhone { get; set; }
        public string EmpEmail { get; set; }
        public Nullable<int> DepId { get; set; }
    }
}
