//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTeacher
    {
        public int tTId { get; set; }
        public string tTName { get; set; }
        public string tTGender { get; set; }
        public Nullable<int> tTAge { get; set; }
        public Nullable<double> tTSalary { get; set; }
        public Nullable<System.DateTime> tTBirthday { get; set; }
        public Nullable<System.DateTime> tTJoinDate { get; set; }
    }
}
